language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install ."
  - "pip install -r test_requirements.txt"

# command to run tests & check style
script:
 - nosetests
 - pep8 courseraoauth2client tests
